"""add tab_switch_count to attempts

Revision ID: d2bb58a1da7e
Revises: 1a6d4b43c599
Create Date: 2026-08-16 13:25:43.525520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2bb58a1da7e'
down_revision = '1a6d4b43c599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_switch_count', sa.Integer(), nullable=False, server_default='0'))



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_column('tab_switch_count')

    # ### end Alembic commands ###
